'use client';
import {useEffect,useState,useRef,type FormEvent,type ReactNode} from 'react';
import {motion,useReducedMotion,useScroll,useSpring} from 'framer-motion';
import {ArrowUpLeft,ArrowUpRight,ArrowDown,Phone,MoveUpRight,Activity,Hand,Leaf,Move,Heart,ClipboardList,Flower2,MessagesSquare,MapPin,Menu,Camera,ChevronLeft,ChevronRight,Plus,Check,Navigation,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetTrigger} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Picture} from '@/components/sections/picture';
import {ClinicVideo} from '@/components/sections/clinic-video';
import {Movement} from '@/components/3d/movement';
import {business,copy,navigation,serviceGroups,gallery,areas,whatsappLink,type Lang} from '@/data/business';
function Reveal({children,className=''}:{children:ReactNode;className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={false} whileInView={reduced?{}:{opacity:[.7,1],y:[16,0]}} viewport={{once:true,amount:.12}} transition={{duration:.7,ease:[.22,1,.36,1]}}>{children}</motion.div>}
export default function SorianaSite({initialLang='ar'}:{initialLang?:Lang}){
 const [lang]=useState<Lang>(initialLang);const t=copy[lang];const rtl=lang==='ar';const Arrow=rtl?ArrowUpLeft:ArrowUpRight;
 const [menuOpen,setMenuOpen]=useState(false);const [active,setActive]=useState('home');const [selectedArea,setSelectedArea]=useState('neck');
 const [filter,setFilter]=useState('all');const [expanded,setExpanded]=useState(false);const [lightbox,setLightbox]=useState<number|null>(null);
 const [service,setService]=useState('');const [formError,setFormError]=useState(false);const [requestUrl,setRequestUrl]=useState('');const [mapOpen,setMapOpen]=useState(false);
 const galleryTrigger=useRef<HTMLButtonElement|null>(null);const statusRef=useRef<HTMLDivElement>(null);
 const {scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:100,damping:30});
 const wa=whatsappLink(t.defaultMessage);const area=areas.find(a=>a.id===selectedArea)!;
 const filtered=gallery.map((item,index)=>({...item,index})).filter(item=>filter==='all'||item.category===filter);const visible=expanded?filtered:filtered.slice(0,6);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=rtl?'rtl':'ltr';},[lang,rtl]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id);});},{rootMargin:'-20% 0px -60% 0px'});document.querySelectorAll('section[id]').forEach(s=>observer.observe(s));return()=>observer.disconnect();},[]);
 const switchLanguage=()=>{window.location.assign(rtl?'/en/':'/');};
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const name=String(data.get('name')||'').trim();const phone=String(data.get('phone')||'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[\s()-]/g,'');const message=String(data.get('message')||'').trim();if(name.length<2||!/^\+?\d{8,15}$/.test(phone)||!service){setFormError(true);setRequestUrl('');return;}setFormError(false);const selected=serviceGroups.flatMap(g=>g.items).find(i=>i.en===service);setRequestUrl(whatsappLink(`${t.defaultMessage}\n${t.name}: ${name}\n${t.phone}: ${phone}\n${t.service}: ${selected?.[lang]||service}${message?`\n${t.message}: ${message}`:''}`));setTimeout(()=>statusRef.current?.focus(),0);}
 const logo=<><span className="brand-icon" aria-hidden="true">S</span><span><strong>{t.shortName}</strong><small>{t.tagline}</small></span></>;
 return <><a className="skip-link" href="#main">{t.skip}</a><motion.div className="reading-progress" style={{scaleX:progress}}/>
 <header className="navigation"><a className="brand" href="#home" aria-label={business.name[lang]}>{logo}</a><nav aria-label={t.menu}>{navigation.map(([id,ar,en])=><a key={id} href={`#${id}`} aria-current={active===id?'location':undefined}>{rtl?ar:en}</a>)}</nav><div className="nav-actions"><button className="language-switch" onClick={switchLanguage} aria-label={rtl?'Switch to English':'التبديل إلى العربية'}>{rtl?'EN':'عربي'}</button><a className="button small" href="#contact">{t.book}<Arrow size={16}/></a><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><button className="mobile-menu icon-button" aria-label={t.menu}><Menu size={23}/></button></SheetTrigger><SheetContent side={rtl?'right':'left'} className="mobile-sheet"><SheetTitle>{t.menu}</SheetTitle><SheetDescription>{business.name[lang]}</SheetDescription><nav>{navigation.map(([id,ar,en])=><a key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{rtl?ar:en}<Arrow size={20}/></a>)}</nav><a className="button" href={wa} target="_blank" rel="noopener noreferrer">{t.whatsapp}<MessagesSquare size={20}/></a></SheetContent></Sheet></div></header>
 <main id="main"><section id="home" className="hero shell"><div className="hero-copy"><span className="eyebrow">{t.eyebrow}</span><h1>{t.heroLines[0]}<br/><em>{t.heroLines[1]}</em><br/>{t.heroLines[2]}</h1><p>{t.intro}</p><div className="hero-buttons"><a className="button" href="#contact">{t.book}<Arrow size={19}/></a><a className="text-link" href="#services">{t.discover}<ArrowDown size={17}/></a></div><div className="hero-note"><span className="mini-line"/><span>{t.heroNote}</span></div></div><div className="hero-visual"><div className="image-arch"><Picture name="physiotherapy-session" alt={gallery[0][lang]} priority/><div className="image-shade"/><div className="image-label"><span>SORIANA · CARE IN MOTION</span><p>{t.photoLabel}</p></div></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><Movement label={t.motion}/><div className="care-tag"><span className="tag-icon"><MoveUpRight/></span><div><strong>{t.careTitle}</strong><small>{t.careNote}</small></div></div><span className="vertical-label">MOVEMENT IS LIFE</span></div><div className="hero-bottom"><a href="#about"><ArrowDown size={16}/>{t.scroll}</a><a href={`tel:${business.telephone}`}><Phone size={15}/><bdi>{business.phoneDisplay}</bdi></a><span>{t.locationShort}</span></div></section>
 <div className="values-strip"><span>{rtl?'رعاية':'Care'}</span><span className="separator"/><span>{rtl?'ثقة':'Trust'}</span><span className="separator"/><span>{rtl?'اهتمام':'Attention'}</span><span className="separator"/><span>{rtl?'حركة':'Movement'}</span></div>
 <section id="about" className="section shell about"><Reveal className="about-photos"><Picture name="clinic-interior" alt={gallery[1][lang]} className="about-large"/><Picture name="wellness-room" alt={gallery[8][lang]} className="about-small" sizes="(max-width: 768px) 40vw, 20vw"/><span className="photo-caption">{t.aboutNote}</span></Reveal><Reveal className="about-copy"><span className="eyebrow">{t.aboutLabel}</span><h2>{t.aboutTitle}</h2><p>{t.aboutText}</p><p>{t.aboutText2}</p><a className="text-link" href="#contact">{t.aboutLink}<Arrow size={18}/></a></Reveal></section>
 <section id="services" className="section services"><div className="shell"><Reveal className="section-heading"><div><span className="eyebrow">{t.servicesLabel}</span><h2>{t.servicesTitle}</h2></div><p>{t.servicesText}</p></Reveal><Tabs defaultValue="therapy" dir={rtl?'rtl':'ltr'} className="services-tabs"><TabsList className="service-tab-list" aria-label={t.servicesLabel}>{serviceGroups.map((g,i)=>{const Icon=[Activity,Hand,Leaf,Move][i];return <TabsTrigger key={g.id} value={g.id}><Icon size={19}/>{g.title[lang]}</TabsTrigger>})}</TabsList>{serviceGroups.map((g,i)=><TabsContent key={g.id} value={g.id} className="service-panel"><div className="service-image"><Picture name={g.image} alt={g.title[lang]}/><span className="service-number">0{i+1}</span></div><div className="service-copy"><span className="eyebrow">{g.title[lang]}</span><h3>{g.lead[lang]}</h3><p>{g.description[lang]}</p><div className="service-chips">{g.items.map(item=><span key={item.en}><Check size={15}/>{item[lang]}</span>)}</div><a className="button" href={whatsappLink(`${t.defaultMessage}\n${t.service}: ${g.title[lang]}`)} target="_blank" rel="noopener noreferrer">{t.inquire}<Arrow size={18}/></a><small>{t.availability}</small></div></TabsContent>)}</Tabs></div></section>
 <section className="section shell pain-section" id="assessment"><Reveal className="pain-copy"><span className="eyebrow">{t.painLabel}</span><h2>{t.painTitle}</h2><p>{t.painText}</p><div className="area-buttons" role="group" aria-label={t.painTitle}>{areas.map(a=><button key={a.id} aria-pressed={selectedArea===a.id} onClick={()=>setSelectedArea(a.id)}>{a[lang]}<Plus size={16}/></button>)}</div><div className="assessment-result" aria-live="polite"><span>{area[lang]}</span><p>{t.painPrompt}</p><a className="text-link" href={whatsappLink(`${t.defaultMessage}\n${rtl?'أرغب بتقييم منطقة':'I would like an assessment for my'}: ${area[lang]}`)} target="_blank" rel="noopener noreferrer">{t.assessment}<Arrow size={18}/></a></div><small className="muted">{t.painNote}</small></Reveal><div className="body-diagram"><div className="body-rings" aria-hidden="true"/><svg viewBox="0 0 200 400" aria-hidden="true" className="body-shape"><defs><linearGradient id="bodyFill" x1="0" x2="1"><stop offset="0" stopColor="#d9dfca"/><stop offset=".5" stopColor="#f0f1e6"/><stop offset="1" stopColor="#bdc9ad"/></linearGradient></defs><path d="M100 15c-22 0-25 14-23 28 1 10 7 15 9 17v12L58 84c-8 4-11 12-13 26L29 194c-2 15 9 18 14 3l21-66 5 64-9 68-2 78-5 22c-2 8 15 12 21 3l8-24 7-72 11-59 11 59 7 72 8 24c6 9 23 5 21-3l-5-22-2-78-9-68 5-64 21 66c5 15 16 12 14-3l-16-84c-2-14-5-22-13-26l-28-12V60c2-2 8-7 9-17 2-14-1-28-23-28Z" fill="url(#bodyFill)" stroke="#b4c2a2" strokeWidth="1"/><path d="M100 77v118M78 91q22 10 44 0M78 158q22 8 44 0" fill="none" stroke="#b6c3a5" strokeWidth="1"/></svg>{areas.map(a=><button key={a.id} className={`body-point ${selectedArea===a.id?'selected':''}`} style={{left:`${a.x/2}%`,top:`${a.y/4}%`}} onClick={()=>setSelectedArea(a.id)} aria-label={a[lang]} aria-pressed={selectedArea===a.id}><span/></button>)}<span className="body-caption" dir="ltr">CARE BEGINS WITH UNDERSTANDING</span></div></section>
 <section id="why" className="section why"><div className="shell"><Reveal className="section-heading"><div><span className="eyebrow">{t.whyLabel}</span><h2>{t.whyTitle}</h2></div><Heart className="why-heart" size={72} strokeWidth={.8}/></Reveal><div className="why-grid">{t.whyItems.map(([title,description],i)=>{const Icon=[Heart,ClipboardList,Flower2,Activity,MessagesSquare][i];return <Reveal key={title} className="why-card"><Icon size={29} strokeWidth={1.3}/><h3>{title}</h3><p>{description}</p></Reveal>})}</div></div></section>
 <section className="section shell journey" id="journey"><Reveal className="center-heading"><span className="eyebrow">{t.journeyLabel}</span><h2>{t.journeyTitle}</h2><p>{t.journeyText}</p></Reveal><div className="journey-steps">{t.steps.map(([title,description],i)=><Reveal key={title} className="journey-step"><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{description}</p></Reveal>)}</div></section>
 <section id="gallery" className="section gallery-section"><div className="shell"><Reveal className="section-heading"><div><span className="eyebrow">{t.galleryLabel}</span><h2>{t.galleryTitle}</h2></div><p>{t.galleryText}</p></Reveal><div className="gallery-filters" role="group" aria-label={t.galleryLabel}>{['all','therapy','clinic','wellness'].map((f,i)=><button key={f} aria-pressed={filter===f} onClick={()=>{setFilter(f);setExpanded(false)}}>{t.filters[i]}</button>)}</div><div className="gallery-grid">{visible.map((g,i)=><button key={g.image} className={`gallery-image gallery-image-${i%6}`} onClick={e=>{galleryTrigger.current=e.currentTarget;setLightbox(g.index)}} aria-label={`${g[lang]} — ${rtl?'تكبير الصورة':'Enlarge image'}`}><Picture name={g.image} alt={g[lang]} sizes="(max-width: 550px) 90vw, (max-width: 800px) 45vw, 30vw"/><span>{g[lang]}<Plus size={22}/></span></button>)}</div>{filtered.length>6&&<button className="button outline gallery-more" onClick={()=>setExpanded(!expanded)}>{expanded?t.showLess:t.showMore}<Plus size={17}/></button>}</div></section>
 <section className="social-section shell"><div><span className="eyebrow">SOCIAL · SORIANA</span><h2>{t.socialTitle}</h2><p>{t.socialText}</p><ClinicVideo lang={lang}/></div><div className="social-links"><a href={business.instagram} target="_blank" rel="noopener noreferrer"><Camera size={22}/><span>Instagram<small>@soriana_physiotherapy</small></span><Arrow size={23}/></a><a href={business.facebook} target="_blank" rel="noopener noreferrer"><span className="facebook-icon" aria-hidden="true">f</span><span>Facebook<small>Soriana Center</small></span><Arrow size={23}/></a></div></section>
 <section id="contact" className="section contact"><div className="shell contact-grid"><Reveal className="contact-copy"><span className="eyebrow">{t.contactLabel}</span><h2>{t.contactTitle}</h2><p>{t.contactText}</p><div className="contact-actions"><a className="button pale" href={wa} target="_blank" rel="noopener noreferrer"><MessagesSquare size={19}/>{t.whatsapp}<Arrow size={18}/></a><a className="button transparent" href={`tel:${business.telephone}`}><Phone size={18}/>{t.call}</a></div><div className="contact-details"><a href={`tel:${business.telephone}`}><Phone size={18}/><bdi>{business.phoneDisplay}</bdi></a><p><MapPin size={20}/>{business.address[lang]}</p><a className="text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(business.mapQuery)}`} target="_blank" rel="noopener noreferrer">{t.directions}<Navigation size={17}/></a></div></Reveal><div className="booking-card"><h3>{t.formTitle}</h3><p>{t.formNote}</p><form onSubmit={submit} noValidate><div className="form-row"><label>{t.name}<input name="name" autoComplete="name" required minLength={2} maxLength={100} placeholder={t.namePlaceholder} aria-invalid={formError||undefined}/></label><label>{t.phone}<input name="phone" type="tel" autoComplete="tel" inputMode="tel" dir="ltr" required maxLength={25} placeholder={t.phonePlaceholder} aria-invalid={formError||undefined}/></label></div><label htmlFor="service">{t.service}</label><Select value={service} onValueChange={setService} dir={rtl?'rtl':'ltr'}><SelectTrigger id="service" className="service-select" aria-invalid={formError||undefined}><SelectValue placeholder={t.selectService}/></SelectTrigger><SelectContent>{serviceGroups.flatMap(g=>g.items).map(item=><SelectItem key={item.en} value={item.en}>{item[lang]}</SelectItem>)}</SelectContent></Select><label>{t.message}<textarea name="message" rows={3} maxLength={1500} placeholder={t.messagePlaceholder}/></label>{formError&&<p className="form-error" role="alert">{t.error}</p>}<button className="button form-submit" type="submit">{t.submit}<Arrow size={18}/></button><small>{t.privacy}</small>{requestUrl&&<div className="form-status" ref={statusRef} tabIndex={-1} role="status"><p>{t.prepared}</p><a className="button" href={requestUrl} target="_blank" rel="noopener noreferrer">{t.openWhatsApp}<Arrow size={18}/></a></div>}</form></div></div></section>
 <section className="map-section shell" aria-label={t.mapTitle}><div className="map-address"><MapPin size={27}/><div><h3>{t.locationShort}</h3><p>{business.address[lang]}</p></div><a className="text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(business.mapQuery)}`} target="_blank" rel="noopener noreferrer">{t.directions}<Arrow size={18}/></a></div>{mapOpen?<iframe className="map-frame" title={t.mapTitle} src={`https://maps.google.com/maps?q=${encodeURIComponent(business.mapQuery)}&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/>:<div className="map-placeholder"><MapPin size={32} strokeWidth={1.3}/><button className="button outline" onClick={()=>setMapOpen(true)}>{t.mapLoad}<Arrow size={18}/></button><small>{t.mapPrivacy}</small></div>}</section>
 </main><footer className="footer shell"><div className="footer-top"><a className="brand" href="#home">{logo}</a><p>{t.footer}</p><a href={`tel:${business.telephone}`} dir="ltr">{business.phoneDisplay}</a></div><nav aria-label={t.menu}>{navigation.map(([id,ar,en])=><a key={id} href={`#${id}`}>{rtl?ar:en}</a>)}</nav><div className="footer-bottom"><span>© {new Date().getFullYear()} {t.shortName}. {t.rights}</span><span>{t.locationShort}</span><div><a href={business.instagram} target="_blank" rel="noopener noreferrer">Instagram</a><a href={business.facebook} target="_blank" rel="noopener noreferrer">Facebook</a></div></div></footer>
 <a className="floating-whatsapp" href={wa} target="_blank" rel="noopener noreferrer" aria-label={t.whatsapp}><MessagesSquare size={25}/><span>{t.whatsapp}</span></a><div className="mobile-cta"><a href={wa} target="_blank" rel="noopener noreferrer"><MessagesSquare size={18}/>{t.whatsapp}</a><a href={`tel:${business.telephone}`}><Phone size={18}/>{t.call}</a><a href="#contact"><Arrow size={18}/>{t.book}</a></div>
 <Dialog open={lightbox!==null} onOpenChange={open=>{if(!open)setLightbox(null)}}><DialogContent className="gallery-lightbox" showCloseButton={false} onCloseAutoFocus={e=>{e.preventDefault();galleryTrigger.current?.focus()}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();setLightbox(n=>((n??0)+1)%gallery.length)}if(e.key==='ArrowLeft'){e.preventDefault();setLightbox(n=>((n??0)-1+gallery.length)%gallery.length)}}}><DialogTitle>{lightbox!==null?gallery[lightbox][lang]:t.galleryTitle}</DialogTitle><DialogDescription className="sr-only">{t.galleryText}</DialogDescription><DialogClose className="lightbox-close icon-button" aria-label={t.close}><X/></DialogClose>{lightbox!==null&&<Picture name={gallery[lightbox].image} alt={gallery[lightbox][lang]} sizes="90vw"/>}<div className="lightbox-controls"><button className="icon-button" aria-label={t.previous} onClick={()=>setLightbox(n=>((n??0)-1+gallery.length)%gallery.length)}><ChevronLeft/></button><span>{(lightbox??0)+1} / {gallery.length}</span><button className="icon-button" aria-label={t.next} onClick={()=>setLightbox(n=>((n??0)+1)%gallery.length)}><ChevronRight/></button></div></DialogContent></Dialog>
 </>;
}



